config/routes.rb
Brandslip::Application.routes.draw do

  resources :user_suggestion_proposals

  resources :brandslip_suggestions

  resources :relationships

  resources :ribbits

  resources :contact_us

  resources :user_job_proposals

  resources :jobs
  
  resource :admin do 
    collection do 
      get 'login'
      post 'create_login'
      get 'logout'
      get 'manage_users'
      get 'manage_posts'
      get 'manage_suggested_posts'      
      get 'manage_bids'
      get 'manage_suggestion_bids'
      get 'manage_reviews'
     
      get 'manage_transactions'
      post 'delete_selected_user'
      post 'delete_selected_posts'
      post 'delete_selected_suggested_posts'
      post 'delete_selected_bids'
      post 'delete_selected_suggestion_bids'
      post 'delete_selected_reviews'
      
      get 'statistics'
      post 'get_weekly_online_posts'
      post 'get_daily_online_posts'
      post 'get_monthly_online_posts'
      get 'payments'

      post 'action_on_selected_user'
      
    end
  end
  get "/remove_account_user" => "brandslip#remove_account_user", :as => :remove_account_user
  get "/touch" => "brandslip#get_in_touch", :as => :get_in_touch
  devise_for :users, :controllers => {:registrations => "registration", :sessions => "devisesession", :passwords => "passwords"}#, :confirmations => "confirmation", :registrations => "registration"}

  root :to => "brandslip#home", constraints: lambda { |r| r.env["warden"].authenticate? }, :as => :dashboard
  root :to => "landing#home", :as => :home
  root :to => "landing#home"
  match "test" => "landing#test", :as => :test
  
  match "new_account_confirm" => "landing#new_account_confirm", :as => :new_account_confirm
  
  match "unfollow" => "relationships#unfollow", :as => :unfollow

  
  match "search_job" => "brandslip#search_job", :as => :search_job
  match "search_job_filter" => "brandslip#search_job_filter", :as => :search_job_filter
  match "search_job_filter_by_location" => "brandslip#search_job_filter_by_location", :as => :search_job_filter_by_location
  match "search_job_filter_by_valid_for" => "brandslip#search_job_filter_by_valid_for", :as => :search_job_filter_by_valid_for
  match "/user_job_detail/:id" => "brandslip#user_job_detail", :as => :user_job_detail
  match "/job_detail/:id" => "brandslip#job_detail", :as => :job_detail

  match "brands_profile" => "profile#brands_profile", :as => :brands_profile
  match "presenters_profile" => "profile#presenters_profile", :as => :presenters_profile
  match "search_profile_filter" => "profile#search_profile_filter", :as => :search_profile_filter
  match "search_brand_filter" => "profile#search_brand_filter", :as => :search_brand_filter
  
  post "/account_remove" => "brandslip#account_remove", :as => :account_remove
  get "/account_remove" => "brandslip#account_remove", :as => :account_remove

  match "send_message" => "brandslip#send_message", :as => :send_message
  match "presenter_profile" => "brandslip#presenter_profile", :as => :presenter_profile
  match "brand_profile" => "brandslip#brand_profile", :as => :brand_profile
  match "presenters_profile_edit" => "brandslip#presenters_profile_edit", :as => :presenters_profile_edit
  match "brands_profile_edit" => "brandslip#brands_profile_edit", :as => :brands_profile_edit
  match "delete_messages" => "brandslip#delete_messages", :as => :delete_messages
  match "presenters_profile_show" => "profile#presenters_profile_show", :as => :presenters_profile_show
  match "brands_profile_show" => "profile#brands_profile_show", :as => :brands_profile_show  
  match "edit_profile" => "brandslip#edit_profile", :as => :edit_profile1
  match "save_user" => "brandslip#save_user", :as => :save_user
  match "delete_job_proposal" => "brandslip#delete_job_proposal", :as => :delete_job_proposal
  match "show_approve_popup" => "brandslip#show_approve_popup", :as => :show_approve_popup
  match "delete_job" => "jobs#delete_job", :as => :delete_job
  match "edit_job_proposal" => "brandslip#edit_job_proposal", :as => :edit_job_proposal
  match "followings_users" => "brandslip#followings_users", :as => :followings_users
  match "followers_users" => "brandslip#followers_users", :as => :followers_users
  match "add_newsfeed" => "brandslip#add_newsfeed", :as => :add_newsfeed
  match "your_posts" => "brandslip#your_posts", :as => :your_posts
  match "delete_post" => "brandslip#delete_post", :as => :delete_post
  match "/jobs/get_cities" => "brandslip#get_cities", :as => :get_cities
  match "edit_bid" => "brandslip#edit_bid", :as => :edit_bid
  match "get_users_to_msg" => "brandslip#get_users_to_msg", :as => :get_users_to_msg
  match "/presenter_mark_done" => "brandslip#presenter_mark_done", :as => :presenter_mark_done
  match "/brand_mark_done" => "brandslip#brand_mark_done", :as => :brand_mark_done
  match "/review_rating" => "brandslip#review_rating", :as => :review_rating
  match "/suggestion_review_rating" => "brandslip#suggestion_review_rating", :as => :suggestion_review_rating
  match "/add_review_rating" => "brandslip#add_review_rating", :as => :add_review_rating
  match "/add_suggestion_review_rating" => "brandslip#add_suggestion_review_rating", :as => :add_suggestion_review_rating
  match "/review" => "brandslip#review", :as => :review
  match "/transaction_history" => "brandslip#transaction_history", :as => :transaction_history
  
  match "/faq" => "brandslip#faq", :as => :faq
 
  match "/policies" => "brandslip#policies", :as => :policies
  match "/our_team" => "brandslip#our_team", :as => :our_team
  match "/terms_conditions" => "brandslip#terms_conditions", :as => :terms_conditions
  match "/contact_us_page" => "brandslip#contact_us_page", :as => :contact_us_page

  match "/accept_bid" => "accept_decline_bid#accept_bid", :as => :accept_bid
  match "/delete_bid" => "accept_decline_bid#delete_bid", :as => :delete_bid
  match "/accept_suggestion_bid" => "accept_decline_bid#accept_suggestion_bid", :as => :accept_suggestion_bid
  match "/delete_suggestion_bid" => "accept_decline_bid#delete_suggestion_bid", :as => :delete_suggestion_bid

  resources :payments, only: [:new] do
    post 'add_card', :on => :collection
    post 'add_bank_account', :on => :collection
    post 'credit', :on => :collection
    post 'debit', :on => :collection
  end
  
  match "delete_suggestion" => "brandslip_suggestions#delete_suggestion", :as => :delete_suggestion
  match "search_suggestion" => "brandslip#search_suggestion", :as => :search_suggestion
  match "/suggestion_detail/:id" => "brandslip#suggestion_detail", :as => :suggestion_detail
  match "/user_suggestion_detail/:id" => "brandslip#user_suggestion_detail", :as => :user_suggestion_detail
  match "edit_suggestion_bid" => "brandslip#edit_suggestion_bid", :as => :edit_suggestion_bid
  match "delete_suggestion_proposal" => "brandslip#delete_suggestion_proposal", :as => :delete_suggestion_proposal
  match "search_suggestion_filter" => "brandslip#search_suggestion_filter", :as => :search_suggestion_filter
  match "search_suggestion_filter_by_location" => "brandslip#search_suggestion_filter_by_location", :as => :search_suggestion_filter_by_location
  match "search_suggestion_filter_by_valid_for" => "brandslip#search_suggestion_filter_by_valid_for", :as => :search_suggestion_filter_by_valid_for  
  
  match "j_save_as_interested" => "brandslip#j_save_as_interested", :as => :j_save_as_interested
  match "j_remove_from_interested" => "brandslip#j_remove_from_interested", :as => :j_remove_from_interested
  match "s_save_as_interested" => "brandslip#s_save_as_interested", :as => :s_save_as_interested
  match "s_remove_from_interested" => "brandslip#s_remove_from_interested", :as => :s_remove_from_interested
  match "interested_brandslips" => "brandslip#interested_brandslips", :as => :interested_brandslips
  match "interested_suggestions" => "brandslip#interested_suggestions", :as => :interested_suggestions
  match "delete_interest_brandslip" => "brandslip#delete_interest_brandslip", :as => :delete_interest_brandslip
  match "delete_interest_suggestion" => "brandslip#delete_interest_suggestion", :as => :delete_interest_suggestion

end

app/views/admins/admin_dashboard_bak1.html.erb
<link href="/assets/admin_css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/style-metro.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/style.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/style-responsive.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin_css/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="/assets/admin_css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="/assets/admin_css/select2_metro.css" />
<link rel="stylesheet" href="/assets/admin_css/DT_bootstrap.css" />
<link rel="shortcut icon" href="favicon.ico" />
<div class="header navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="brand" href="<%= admin_dashboard_path %>">
        BrandSlip Admin
      </a>
      <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <img src="/assets/admin/menu-toggler.png" alt="" />
      </a>                    
      <ul class="nav pull-right">
        <!-- BEGIN NOTIFICATION DROPDOWN -->   
        <li class="dropdown" id="header_notification_bar">

        </li>
        <!-- END NOTIFICATION DROPDOWN -->
        <!-- BEGIN INBOX DROPDOWN -->
        <li class="dropdown" id="header_inbox_bar">

          <ul class="dropdown-menu extended inbox">

          </ul>
        </li>
        <!-- END INBOX DROPDOWN -->
        <!-- BEGIN TODO DROPDOWN -->
        <li class="dropdown" id="header_task_bar">

        </li>
        <!-- END TODO DROPDOWN -->               
        <!-- BEGIN USER LOGIN DROPDOWN -->
        <li class="dropdown user">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <img alt="" src="/assets/admin/avatar1_small.jpg" />
            <span class="username">Kofi Frimpong</span>
            <i class="icon-angle-down"></i>
          </a>
          <ul class="dropdown-menu">
            <li><a href="extra_profile.html"><i class="icon-user"></i> My Profile</a></li>
            <li><a href="page_calendar.html"><i class="icon-calendar"></i> My Calendar</a></li>
            <li><a href="inbox.html"><i class="icon-envelope"></i> My Inbox <span class="badge badge-important">3</span></a></li>
            <li><a href="#"><i class="icon-tasks"></i> My Tasks <span class="badge badge-success">8</span></a></li>
            <li class="divider"></li>
            <li><a href="javascript:;" id="trigger_fullscreen"><i class="icon-move"></i> Full Screen</a></li>
            <li><a href="extra_lock.html"><i class="icon-lock"></i> Lock Screen</a></li>
            <li><a href="<%= admin_logout_path %>"><i class="icon-key"></i> Log Out</a></li>
          </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->
        <!-- END USER LOGIN DROPDOWN -->
      </ul>
      <!-- END TOP NAVIGATION MENU --> 
    </div>
  </div>
  <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->
<!-- BEGIN CONTAINER -->
<div class="page-container row-fluid">
  <!-- BEGIN SIDEBAR -->
  <div class="page-sidebar nav-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->        
    <ul class="page-sidebar-menu">
      <li>
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        <div class="sidebar-toggler hidden-phone"></div>
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
      </li>
      <li>
        <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
        <form class="sidebar-search">
          <div class="input-box">
            <a href="javascript:;" class="remove"></a>
            <input type="text" placeholder="Search..." />
            <input type="button" class="submit" value=" " />
          </div>
        </form>
        <!-- END RESPONSIVE QUICK SEARCH FORM -->
      </li>
      <li class="start ">
        <a href="<%= admin_dashboard_path %>">
          <i class="icon-home"></i> 
          <span class="title">Dashboard</span>
        </a>
      </li>      
    </ul>
    <!-- END SIDEBAR MENU -->
  </div>
  <!-- END SIDEBAR -->
  <!-- BEGIN PAGE -->
  <div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="portlet-config" class="modal hide">
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button"></button>
        <h3>Widget Settings</h3>
      </div>
      <div class="modal-body">
        Widget Settings form goes here
      </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
      <!-- BEGIN PAGE HEADER-->
      <div class="row-fluid">
        <div class="span12">

          <!-- BEGIN PAGE TITLE & BREADCRUMB-->
          <h3 class="page-title">
            Dashboard <small>admin dashboard</small>
          </h3>
          <ul class="breadcrumb">
            <li>
              <i class="icon-home"></i>
              <a href="<%= admin_dashboard_path %>">Home</a> 
              <i class="icon-angle-right"></i>
            </li>
            <li><a href="#">Dashboard</a></li>
          </ul>
          <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
        
        <div class="row-fluid">
          <div class="span12">
              <!-- BEGIN EXAMPLE TABLE PORTLET-->
              <div class="portlet box green">
                  <div class="portlet-title">
                          <div class="caption"><i class="icon-globe"></i>BrandSlip users</div>
        
                  </div>
                  <div class="portlet-body">
                          <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                              <thead>  
                                <tr>
                                  <th><input type="checkbox" id="select_all_users" onchange=""/></th>
                                  <th>Name</th>
                                  <th>Email</th>
                                  <th>Status</th>
                                  <th>Created On</th>
                                </tr>
                              </thead>
                            <tbody>
                              <% @users.each do |user| %>
                              <tr id="tr_<%= user.id %>">
                                <td><label class="checkbox"><input id="brandslip_user" type="checkbox" value="<%= user.id %>" onchange=""/></label></td>
                                <td><%= user.first_name %> <%= user.last_name %></td>
                                <td><%= user.email %></td>
                                <% if user.is_approved == 0 %>
                                  <td id="td_status" style="color:#08C">New</td>
                                <% elsif user.is_approved == 1 %>
                                  <td id="td_status" style="color:green">Approved</td>
                                <% else %>
                                  <td id="td_status" style="color:red">Rejected</td>
                                <% end %>
                                <td><%= user.created_at %></td>
                              </tr>
                              <% end %>
                            </tbody>                              
                          </table>
                  </div>
              </div>
              <div style="padding-left: 450px">
                <input type="button" class="btn green" value="Approve"  onclick="approve_selected_users('approve')">
                <input type="button" class="btn red" value="Delete"  onclick="delete_selected_users()">
                <input type="button" class="btn red" value="Reject"  onclick="approve_selected_users('reject')">

                <%= image_tag("loader.gif",  :id => "ajaxloading", :style => "display:none") %>
                <span id="success_msg"></span>
              </div>              
          </div>
      </div>

    </div>
    <!-- END PAGE CONTAINER-->    
  </div>
  <!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="footer">
  <div class="footer-inner">
    2013 &copy; Metronic by keenthemes.
  </div>
  <div class="footer-tools">
    <span class="go-top">
      <i class="icon-angle-up"></i>
    </span>
  </div>
</div>
<!-- END FOOTER -->
<script src="/assets/admin/jquery-1.10.1.min.js" type="text/javascript"></script>
<script src="/assets/admin/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
<script src="/assets/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/admin/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script> 
<script src="/assets/admin/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/admin/jquery.blockui.min.js" type="text/javascript"></script>  
<script src="/assets/admin/jquery.cookie.min.js" type="text/javascript"></script>
<script src="/assets/admin/jquery.uniform.min.js" type="text/javascript" ></script>
<script type="text/javascript" src="/assets/admin/select2.min.js"></script>
<script type="text/javascript" src="/assets/admin/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/admin/DT_bootstrap.js"></script>
<script src="/assets/admin/app.js"></script>   
<script src="/assets/admin/admin.js"></script>   

<script>
  jQuery(document).ready(function() {
    // initiate layout and plugins
    App.init();    
  });
</script>

app/views/admins/admin_login_bak.html.erb
<div>
    <div class="signuplogo" style="padding-top: 50px;padding-bottom: 25px;text-align: center;">Brandslip</div>
    <div style="padding-left: 35%">
      <div class="error"><%= notice %></div>
      <form action="/admin/authentication">
        <div class="input-group">
          <span class="input-group-addon input-large">@</span>
          <input id="admin_email" name="admin_email" type="email" class="form-control input-large" placeholder="Username">
        </div>        

        <div class="input-group">
          <span class="input-group-addon input-large">@</span>
          <input id="admin_password" name="admin_password" size="30" type="password"  class="form-control input-large" placeholder="Password">
        </div>           
        <div style="margin-top: 15px">
          <input name="commit" style="width: 53%" class="btn btn-primary btn-large" type="submit" value="Admin Log in">
        </div>
      </form>
    </div>
</div>

app/views/admins/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>BrandSlip | Login Page</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<link href="/assets/admin_css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/style-metro.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/style.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/admin_css/login.css" rel="stylesheet" type="text/css"/>
	<link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
	<!-- BEGIN LOGO -->
        <div class="logo" style="color: yellow">
		BrandSlip Admin
	</div>
        <div style="width: 247px;margin: 0 auto;color: red;padding: 15px;text-align: center;"><%= notice %></div>
	<!-- END LOGO -->
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGIN FORM -->
		<form class="form-vertical login-form" action="<%= create_login_admin_url %>" method="post">
			<h3 class="form-title">Login your admin account</h3>
			<div class="alert alert-error hide">
				<button class="close" data-dismiss="alert"></button>
				<span>Enter any username and password.</span>
			</div>
			<div class="control-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Username</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-user"></i>
						<input class="m-wrap placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="admin_email"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9">Password</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-lock"></i>
						<input class="m-wrap placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="admin_password"/>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<label class="checkbox">
				<input type="checkbox" name="remember" value="1"/> Remember me
				</label>
				<button type="submit" class="btn green pull-right">
				Login <i class="m-icon-swapright m-icon-white"></i>
				</button>            
			</div>
		</form>
		<!-- END LOGIN FORM -->        


	</div>
	<!-- END LOGIN -->
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		2013 &copy; BrandSlip.
	</div>
	<script src="/assets/admin/jquery-1.10.1.min.js" type="text/javascript"></script>
	<script src="/assets/admin/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
	<script src="/assets/bootstrap.min.js" type="text/javascript"></script>
	<script src="/assets/admin/jquery.validate.min.js" type="text/javascript"></script>	    
	<script src="/assets/admin/app.js" type="text/javascript"></script>
	<script src="/assets/admin/login.js" type="text/javascript"></script> 
	<script>
		jQuery(document).ready(function() {     
		  App.init();
		  Login.init();
		
		 
		
		});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

app/views/admins/manage_bids.html.erb
  <div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="portlet-config" class="modal hide">
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button"></button>
        <h3>Widget Settings</h3>
      </div>
      <div class="modal-body">
        Widget Settings form goes here
      </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
      <!-- BEGIN PAGE HEADER-->
      <div class="row-fluid">
        <div class="span12">

          <!-- BEGIN PAGE TITLE & BREADCRUMB-->
          <h3 class="page-title">
            Manage Bids <small>admin dashboard</small>
          </h3>
          <ul class="breadcrumb">
            <li>
              <i class="icon-home"></i>
              <a href="<%= manage_bids_admin_path %>">Home</a> 
              <i class="icon-angle-right"></i>
            </li>
            <li><a href="">Manage Bids</a></li>
          </ul>
          <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
        
        <div class="row-fluid">
          <div class="span12">
              <!-- BEGIN EXAMPLE TABLE PORTLET-->
              <div class="portlet box green">
                  <div class="portlet-title">
                          <div class="caption"><i class="icon-globe"></i>All Proposals</div>
        
                  </div>
                  <div class="portlet-body">
                          <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                              <thead>  
                                <tr>
                                  <th><input type="checkbox" id="select_all_users" onchange=""/></th>
                                  <th>Job Title</th>
                                  <th>Bid Text</th>
                                  <th>Cost</th>
                                  <th>By User</th>
                                  <th>Created on</th>
                                </tr>
                              </thead>
                            <tbody>
                              <% @bids.each do |bid| %>
                              <tr id="tr_<%= bid.id %>">
                                <td><label class="checkbox"><input id="brandslip_user" type="checkbox" value="<%= bid.id %>" onchange=""/></label></td>
                                <td><%= get_job_title(bid.job_id) %></td>
                                <td>                                  
                                  <span title="<%= bid.proposal_details %>" style="width:100px;"><%= bid.proposal_details.length>49? (bid.proposal_details[0..49]+' ...'): bid.proposal_details %></span>
                                </td>
                                <td><%= bid.proposal_cost %></td>
                                <td><%= get_user_name(bid.user_id) %></td>
                                <td><%= bid.created_at %></td>
                              </tr>
                              <% end %>
                            </tbody>                              
                          </table>
                    </div>
              </div>
              <div style="padding-left: 450px">                
                <input type="button" class="btn red" value="Cancel Selected"  onclick="delete_selected_bids()">
                <%= image_tag("loader.gif",  :id => "ajaxloading", :style => "display:none") %>
                <span id="success_msg"></span>
              </div>              
          </div>
      </div>

    </div>
    <!-- END PAGE CONTAINER-->    
  </div>

app/views/admins/manage_posts.html.erb
  <div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="portlet-config" class="modal hide">
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button"></button>
        <h3>Widget Settings</h3>
      </div>
      <div class="modal-body">
        Widget Settings form goes here
      </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
      <!-- BEGIN PAGE HEADER-->
      <div class="row-fluid">
        <div class="span12">

          <!-- BEGIN PAGE TITLE & BREADCRUMB-->
          <h3 class="page-title">
            Manage Posts <small>admin dashboard</small>
          </h3>
          <ul class="breadcrumb">
            <li>
              <i class="icon-home"></i>
              <a href="<%= manage_posts_admin_path %>">Home</a> 
              <i class="icon-angle-right"></i>
            </li>
            <li><a href="#">Manage Posts</a></li>
          </ul>
          <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
        
        <div class="row-fluid">
          <div class="span12">
              <!-- BEGIN EXAMPLE TABLE PORTLET-->
              <div class="portlet box green">
                  <div class="portlet-title">
                    <div class="caption"><i class="icon-globe"></i>All BrandSlips</div>        
                  </div>
                  <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                        <thead>  
                          <tr>
                            <th><input type="checkbox" id="select_all_users" onchange=""/></th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th>By User</th>
                            <th>Created On</th>
                          </tr>
                        </thead>
                      <tbody>
                        <% @posts.each do |post| %>
                        <tr id="tr_<%= post.id %>">
                          <td><label class="checkbox"><input id="brandslip_user" type="checkbox" value="<%= post.id %>" onchange=""/></label></td>
                          <td><%= post.job_title %></td>
                          <td><%= get_category_name(post.job_category) %></td>                                
                          <td><%= post.job_price_fixed_type %></td>
                          <td><%= get_user_name(post.job_user_id) %></td>
                          <td><%= post.created_at %></td>
                        </tr>
                        <% end %>
                      </tbody>                              
                    </table>
                  </div>
              </div>
              <div style="padding-left: 450px">                
                <input type="button" class="btn red" value="Delete Selected"  onclick="delete_selected_posts()">
                <%= image_tag("loader.gif",  :id => "ajaxloading", :style => "display:none") %>
                <span id="success_msg"></span>
              </div>              
          </div>
      </div>

    </div>
    <!-- END PAGE CONTAINER-->    
  </div>